name: baaba_starter_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  fpdart: ^1.2.0
  get_it: ^8.2.0
  injectable: ^2.5.2
  internet_connection_checker_plus: ^2.9.1
  shared_preferences: ^2.5.3
  get: ^4.7.2
  share_plus: ^12.0.1
  baaba_api_services:
    git: https://github.com/zunairpervaiz/baaba-api-services.git
  envied: ^1.3.1
  localization: ^2.1.1
  flutter_localization: ^0.3.3
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  injectable_generator: ^2.9.0
  build_runner: ^2.10.1
  package_rename: ^1.10.0
  flutter_gen_runner: ^5.12.0
  flutter_launcher_icons: ^0.14.4
  envied_generator: ^1.3.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/env/
    - assets/fonts/

flutter_gen:
  output: lib/app/generated/
  line_length: 140
  integrations:
    flutter_svg: true
  assets:
    exclude:
      - assets/app_icon.png

flutter_launcher_icons:
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true
  android: true
  ios: true

package_rename_config:
  android:
    app_name: "Baaba Starter Project"
    package_name: "com.example.baaba"
  ios:
    app_name: "Baaba Starter Project"
    package_name: "com.example.baaba"
